### PR TITLE
Parso library update

### PR DESCRIPTION
**Pull request by mulya**
Parso library update #10 
- bumped version of "parso" dependency and updated groupId
- replaced own implementation of SasFileParser with reflection hacks of parso's SasFileParser
- implemented SasFileParserWrapper to encapsulate all reflection hacks
- removed rules of merge class files for assembly sbt plugin

### CODE REVIEW

**Comment by mulya** [comment]
I think I can find big sas7bdat file easily and check is everything is ok. I'll do it tomorrow and let you know.

**Comment by mulya** [comment]
I've found 2Gb sas7bdat file and tried to convert it to CSV - everything is alright. By the way this file was from #18, I've tried conversion by versions of code before my changes and after and still can not reproduce the error, so I think you can close this issue as non-reproducable.

**Comment by JamesWrigley** [comment]
As an aside, this should also fix #23 (see epam/parso@df7489de27553a219a46651337df518832760cff).

**Comment by Tagar** [comment]
@saurfang unfortunately what's a high priority for Engineering not always same priority for legal folks .. I understand it's so low on their list so we shouldn't be waiting for them if there is another commit does a similar change. thanks a lot!

**Comment by saurfang** [comment]
@Tagar I understand.Since you also tested your upgrade patch, I was just wondering if you can review this PR to see if this is more or less what you did and if you had any insights for potential pitfalls to look out.

@mulya Sounds like this is working well enough at least for you. I will see if I can find some time this weekend to put together a release. Thanks again for your contribution. This upgrade has been a long-standing ask from many users.

**Pull request merged**
